### ISSUE TITLE
How to run

### ISSUE THREAD

**Issue by tsuiwade** [ulises214/flutter-weather-app#1]
Hi guy!
I'm running on web , but only showing `Loading` .

What should I do ?

**Comment by ulises214** [comment]
> Hi guy!
> I'm running on web , but only showing `Loading` .
> 
> What should I do ?

Oh I'm sorry, this only a practice, then I did it just thinking in my Samsung S10 (permissions, performance, sizes) :(
I realized that on the web it fails coz the library that I use for the permissions management doesn't work in flutter web
I'm sorry to disappoint you.  :(

**Comment by tsuiwade** [comment]
I'm sorry to disturb you again.
After serching many days, I still feel sorry for not being able to reproduce your work.

It's said that flutter is cross platform, maybe your work can run on `chrome` with a little modification.

Sincerely, please help me.

Your perfect job can help a lot of people.

**Comment by ulises214** [comment]
> I'm sorry to disturb you again.
> After serching many days, I still feel sorry for not being able to reproduce your work.
> 
> It's said that flutter is cross platform, maybe your work can run on `chrome` with a little modification.
> 
> Sincerely, please help me.
> 
> Your perfect job can help a lot of people.

How I say, it's just a practice, there are a lot of features that I would like to implement
Anyways, I will research and fix the web problem next week
